name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  ci-pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Dependencies
        run: npm ci
      - name: Lint TypeScript
        run: npm run lint:ts
      - name: Lint Styles
        run: npm run lint:scss
      - name: Run Unit Tests
        run: npm run test:unit
      - name: Build Storybook
        run: npm run storybook:build
      - name: Run Screenshot Tests
        run: npm run test:ui:ci
      - name: Build Production Bundle
        run: npm run build:prod
